dpkg-deb -bZgzip projects/AppCake debs
dpkg-deb -bZgzip projects/AppSyncUnified debs
dpkg-deb -bZgzip projects/com.Misti.loveiscomplicatedagain debs
dpkg-deb -bZgzip projects/CyDown debs
dpkg-deb -bZgzip projects/Failsafe debs
dpkg-deb -bZgzip projects/Falcon debs
dpkg-deb -bZgzip projects/IAPCrazy debs
dpkg-deb -bZgzip projects/KGPayphone debs
dpkg-deb -bZgzip projects/LocalIAPStore debs
dpkg-deb -bZgzip projects/OpenNotifier10 debs
dpkg-deb -bZgzip projects/Phantom debs
dpkg-deb -bZgzip projects/PriorityHub debs
dpkg-deb -bZgzip projects/SnapCrack debs
dpkg-deb -bZgzip projects/TouchHome debs
dpkg-deb -bZgzip projects/TweakMode debs