#!/bin/bash

chown root:wheel /var/mobile/Library/IconTool/itr
chmod a+x /var/mobile/Library/IconTool/itr
chmod u+s /var/mobile/Library/IconTool/itr

chown root:wheel /var/mobile/Library/IconTool/itc
chmod a+x /var/mobile/Library/IconTool/itc
chmod u+s /var/mobile/Library/IconTool/itc

chown -R mobile:mobile /var/mobile/IconTool/
chmod -R 0755 /var/mobile/IconTool/

icosv=`sysctl -n kern.osversion`
icosvp=`echo ${icosv:0:2}`

if [ "$icosvp" == "12" ]; then
  cp /var/mobile/Library/IconTool/IconTool8.dylib /Library/MobileSubstrate/DynamicLibraries/IconTool.dylib
elif [ "$icosvp" == "13" ]; then
  cp /var/mobile/Library/IconTool/IconTool9.dylib /Library/MobileSubstrate/DynamicLibraries/IconTool.dylib
elif [ "$icosvp" == "14" ]; then
  cp /var/mobile/Library/IconTool/IconTool9.dylib /Library/MobileSubstrate/DynamicLibraries/IconTool.dylib
else
  cp /var/mobile/Library/IconTool/IconTool.dylib /Library/MobileSubstrate/DynamicLibraries/IconTool.dylib
fi

chown 0:0 /Library/MobileSubstrate/DynamicLibraries/IconTool.dylib
chmod a+x /Library/MobileSubstrate/DynamicLibraries/IconTool.dylib


