#!/bin/sh

mkdir /var/mobile/Media/AppCake
mkdir /var/mobile/Media/AppCake/Download5
mkdir /var/mobile/Media/AppCake/Imported
mkdir /var/mobile/Media/AppCake/BTDownloads
chmod 777 -R /var/mobile/Media/AppCake

mkdir /var/mobile/Documents/asiDownload/Temp
chmod 777 -R /var/mobile/Documents/asiDownload/Temp

rm -rf /var/mobile/Library/Caches/SDDataCache
rm -rf /var/mobile/Library/Caches/default/com.hackemist.SDWebImageCache.default

launchctl stop com.apple.mobile.installd
launchctl start com.apple.mobile.installd

killall -9 AppCake

su -c uicache mobile

declare -a cydia
cydia=($CYDIA)
if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >&${cydia[0]}"
fi
exit 0